version: "3.8"

services:
  db:
    image: postgres:10.1-alpine
    restart: always
    env_file:
      - .env

  web:
    restart: always
    build:
      context: .
    volumes:
      - .:/app
    env_file:
        - .env
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8004:8000
    depends_on:
      - db